In [2]:
import numpy as np

In [3]:
score = np.array([12, 20, 5, 18])
print(score)

[12 20  5 18]


In [4]:
print(score.ndim) # 1
print(score.shape) # (4, )

1
(4,)


In [5]:
s = np.sort(score)
print(s)

[ 5 12 18 20]


In [6]:
print(score)

[12 20  5 18]


In [7]:
uscore = np.unique(score)

In [8]:
uscore

array([ 5, 12, 18, 20])

In [9]:
x = score / 2
print(x)

[ 6.  10.   2.5  9. ]


In [10]:
print(x, score, end= '\n')

[ 6.  10.   2.5  9. ] [12 20  5 18]


In [11]:
np.sum(score)

55

In [12]:
score_2 = np.where(score < 10, 10, 20)
print(score_2)

[20 20 10 20]


In [13]:
print(np.where(score == 12))
print(score)

(array([0]),)
[12 20  5 18]


In [14]:
print(np.where(score%2 == 0))

(array([0, 1, 3]),)


In [15]:
score_copy = score.copy()
print(score_copy)
print(score)

[12 20  5 18]
[12 20  5 18]


In [16]:
score[2] = 5
print(score) # [5, 12, 5, 20]

[12 20  5 18]


In [17]:
print(score_copy)

[12 20  5 18]


In [18]:
score_view = score.view()
print(score)
print(score_view)

[12 20  5 18]
[12 20  5 18]


In [19]:
score[2] = 18
print(score)
print(score_view)

[12 20 18 18]
[12 20 18 18]


In [20]:
score_15_sort = np.searchsorted(score, 15)
print(score_15_sort)

1


In [21]:
lst_a = [12, 9, 18]
arr_a = np.array(lst_a)
filt_a = [True, False, True]
print(arr_a[filt_a])

[12 18]


In [22]:
print(np.zeros(3)) # [0, 0, 0]
print(np.full(3, 20)) # [20, 20, 20]
print(np.arange(3)) # [0, 1, 2]
print(np.random.rand(3)) # [0 < 1, ..., ...]

[0. 0. 0.]
[20 20 20]
[0 1 2]
[0.15686045 0.55010207 0.85584933]


In [23]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
tuple_ab = (a, b)
c = np.concatenate(tuple_ab)
print(c)

[1 2 3 4 5 6]


In [24]:
print(c.ndim) # 1
print(c.shape) # (6, )

1
(6,)


In [25]:
b = np.array_split(c, 2)
print(b)

[array([1, 2, 3]), array([4, 5, 6])]


In [26]:
print(b[0][0]) # 1
print(b[1][2]) # 6

1
6


In [27]:
score = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(score)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [28]:
print(score.ndim) # 2
print(score.shape) # (3, 2)

2
(3, 3)


In [29]:
a = score
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [30]:
print(
a[0], # [1, 2, 3]
a[0][0], # [1]
a[1][1], # [5]
a[-1][-1], # [9]
a[0][-1], # [3]
a[-1][0], # [7]
a[0, 1:3], # [2, 3]
a[1, 1:4], # [5, 6]
)

[1 2 3] 1 5 9 3 7 [2 3] [5 6]


In [31]:
a = np.array([1, 2, 3, 4])
b = a.reshape(2, 2)
print(a, '\n')
print(b)

[1 2 3 4] 

[[1 2]
 [3 4]]


In [32]:
score

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
print(np.sum(score))
np.sum(score, axis= 1)
"""
[[6]
 [15]
 [24]]
"""

45


'\n[[6]\n [15]\n [24]]\n'

In [42]:
a = np.random.randint(0, 100, size= (3, 4))
print(a, '\n')
print(np.sum(a, axis= 0))

[[17 62 17 28]
 [94 23 83  5]
 [35 10 77 86]] 

[146  95 177 119]


In [48]:
a = np.random.randint(0, 100, size= (3, 4))
b = np.random.randint(0, 100, size= (3, 4))
print(np.concatenate((a, b)), '\n')
print(np.concatenate((a, b), axis= 0), '\n')
print(np.concatenate((a, b), axis= 1), '\n')

[[ 8 37 12 63]
 [73 51 44 24]
 [62 51 43 87]
 [79 36 57 72]
 [79  8 16 80]
 [21 12 85  3]] 

[[ 8 37 12 63]
 [73 51 44 24]
 [62 51 43 87]
 [79 36 57 72]
 [79  8 16 80]
 [21 12 85  3]] 

[[ 8 37 12 63 79 36 57 72]
 [73 51 44 24 79  8 16 80]
 [62 51 43 87 21 12 85  3]] 



In [54]:
a = np.random.randint(0, 100, size= (4, 3))
print(a, '\n')
print(a.swapaxes(1, 0))

[[ 8 14 52]
 [42 46  1]
 [60 49 43]
 [ 4 84 84]] 

[[ 8 42 60  4]
 [14 46 49 84]
 [52  1 43 84]]
